cookie:
  expiry_days: 30
  key: some_signature_key
  name: some_cookie_name
credentials:
  usernames:
    alisha:
      email: alishatest@gmail.com
      logged_in: false
      name: alisha
      ownedbadges:
      - 0
      password: $2b$12$TAeJ28Desd5US6Lmu0RbVurVLmC0ci7Sjemtr7FU99hmddiXGm3tq
      points: 20
      selectbadgeid: 0
    gurjodh:
      email: Gurjodhtest@gmail.com
      logged_in: true
      name: Gurjodh
      ownedbadges:
      - 3
      - 4
      - 7
      - 2
      - 1
      - 5
      password: $2b$12$pEdBh121Q6ylKI34tpncv.Tpvo4L62no.kNBkXb17Crevg/0SgTa2
      points: 0
      selectbadgeid: 7
    jasdeep:
      email: jasdeeptest@gmail.com
      logged_in: false
      name: jasdeep
      ownedbadges:
      - 0
      - 1
      - 7
      password: $2b$12$XQoWTTZCHAXSdH1WLXeDUeOkktzF9bYdY.sOHsyDMufkQ0eHc.cni
      points: 420
      selectbadgeid: 0
preauthorized:
  emails: null
